[package]
name = "boids"
version = "0.1.0"
authors = ["Daniel Hammer <HammerAPI@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
macroquad = "0.4.7"
rand = "0.8.5"
